/etc/radm/version NORMAL
/etc/radm/fingerprint NORMAL
/opt/radm/hardening NORMAL
/opt/radm/xdp NORMAL
/opt/radm/runtime NORMAL
/opt/radm/tools NORMAL
/usr/local/bin/radm-* NORMAL
/etc/systemd/system/radm-*.service NORMAL
!/var/log
!/var/lib/docker
!/data
!/tmp