# Network protocols (securite)
blacklist dccp
blacklist sctp
blacklist rds
blacklist tipc
blacklist decnet
blacklist ax25
blacklist netrom
blacklist x25
blacklist appletalk
blacklist ipx
blacklist nf_conntrack

# Filesystems
blacklist cramfs
blacklist freevxfs
blacklist jffs2
blacklist hfs
blacklist hfsplus
blacklist squashfs

# USB (pour appliance securisee)
blacklist usb-storage

# Firewire
blacklist firewire-core