/var/log/*.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    notifempty
    maxsize 1G
    sharedscripts
    postrotate
        systemctl kill -s HUP rsyslog 2>/dev/null || true
    endscript
}
/opt/radm/runtime/logs/*.log {
    daily
    rotate 7
    compress
    delaycompress
    missingok
    maxsize 500M
}