# RADM AI v3.0 - SNMPv3 Configuration (ANSSI compliant)
agentAddress udp:127.0.0.1:161
rwuser radm priv
view systemview included .1.3.6.1.2.1.1
view systemview included .1.3.6.1.2.1.2
view systemview included .1.3.6.1.2.1.25
rouser radm authPriv
disableV1V2c yes
logOption f /var/log/snmpd.log